// <auto-generated />
using System;
using GradeProgressMonitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradeProgressMonitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227210325_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradeProgressMonitoring.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("StudentProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ClassOffering", b =>
                {
                    b.Property<int>("ClassOfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassOfferingId"));

                    b.Property<int>("ClassType")
                        .HasColumnType("integer");

                    b.Property<string>("CourseYearSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Days")
                        .HasColumnType("text");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<decimal>("Units")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("ClassOfferingId");

                    b.HasIndex("SubjectCode", "Term", "SchoolYear", "CourseYearSection", "ClassType")
                        .IsUnique();

                    b.ToTable("ClassOfferings");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ComponentItem", b =>
                {
                    b.Property<int>("ComponentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentItemId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("GradingComponentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpenForEncoding")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.HasKey("ComponentItemId");

                    b.HasIndex("GradingComponentId");

                    b.ToTable("ComponentItems");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassOfferingId")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("StudentProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentUserId")
                        .HasColumnType("text");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("ClassOfferingId", "StudentNo")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.GradingComponent", b =>
                {
                    b.Property<int>("GradingComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradingComponentId"));

                    b.Property<int>("ClassOfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WeightPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("GradingComponentId");

                    b.HasIndex("ClassOfferingId");

                    b.ToTable("GradingComponents");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabActivitySubmission", b =>
                {
                    b.Property<int>("LabActivitySubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabActivitySubmissionId"));

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("integer");

                    b.Property<int>("DaysLate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EncodedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPlagiarized")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LabActivitySubmissionId");

                    b.HasIndex("ComponentItemId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("LabActivitySubmissions");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabRubricCriterion", b =>
                {
                    b.Property<int>("LabRubricCriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabRubricCriterionId"));

                    b.Property<int>("GradingComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("WeightPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("LabRubricCriterionId");

                    b.HasIndex("GradingComponentId");

                    b.ToTable("LabRubricCriteria");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabRubricScore", b =>
                {
                    b.Property<int>("LabRubricScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabRubricScoreId"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("LabActivitySubmissionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("LabRubricScoreId");

                    b.HasIndex("LabActivitySubmissionId");

                    b.ToTable("LabRubricScores");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ScoreEntry", b =>
                {
                    b.Property<int>("ScoreEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreEntryId"));

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EncodedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncodedByUserId")
                        .HasColumnType("text");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScoreEntryId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("ComponentItemId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentProfileId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Program")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StudentNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("YearLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("StudentProfileId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.SubjectCatalog", b =>
                {
                    b.Property<int>("SubjectCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCatalogId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Program")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SubjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Units")
                        .HasColumnType("numeric");

                    b.Property<string>("YearLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SubjectCatalogId");

                    b.ToTable("SubjectCatalogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GradeProgressMonitoring.Data.ApplicationUser", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ComponentItem", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.GradingComponent", "GradingComponent")
                        .WithMany("Items")
                        .HasForeignKey("GradingComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingComponent");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.Enrollment", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.ClassOffering", "ClassOffering")
                        .WithMany()
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeProgressMonitoring.Models.StudentProfile", "StudentProfile")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", "StudentUser")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassOffering");

                    b.Navigation("StudentProfile");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.GradingComponent", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.ClassOffering", "ClassOffering")
                        .WithMany("Components")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabActivitySubmission", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.ComponentItem", "ComponentItem")
                        .WithMany()
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentItem");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabRubricCriterion", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.GradingComponent", "GradingComponent")
                        .WithMany("LabRubricCriteria")
                        .HasForeignKey("GradingComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingComponent");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabRubricScore", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.LabActivitySubmission", "Submission")
                        .WithMany("RubricScores")
                        .HasForeignKey("LabActivitySubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ScoreEntry", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Models.ComponentItem", "ComponentItem")
                        .WithMany()
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", "StudentUser")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentItem");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GradeProgressMonitoring.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.ClassOffering", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.GradingComponent", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LabRubricCriteria");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.LabActivitySubmission", b =>
                {
                    b.Navigation("RubricScores");
                });

            modelBuilder.Entity("GradeProgressMonitoring.Models.StudentProfile", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
